version: "3"

services:

  # # The craffic reactjs_web service is responsible for running our webclient.
  # reactjs_web:
  #   container_name: reactjs_web
  #   build:
  #     # Tell Docker which files should be sent to the Docker daemon
  #     context: ./web
  #     # Tell compose to only run the 'development' stage of the docker file
  #     target: development
  #   volumes:
  #   - ./web:/usr/src/app
  #   - /usr/src/app/node_modules
  #   ports:
  #   - ${REACTJS_PORT}:${REACTJS_PORT}
  #   # This runs after development stage is done
  #   command: react-scripts start
  #   env_file:
  #   - ./web/.docker.env
  #   networks:
  #   - postgres
  #   depends_on:
  #   - redis
  #   - postgres

  # The craffic nestjs_server service is responsible for running our server and API.
  nestjs-server:
    container_name: nestjs-server
    build:
      # Tell Docker which files should be sent to the Docker daemon
      context: ./server/
      # Tell compose to only build the 'development' stage of the docker file
      target: development
    volumes:
    # Make development dir available in container
    - ./server:/usr/src/app
    # Make node_modules available in container
    - /usr/src/app/node_modules
    ports:
    - ${NESTJS_PORT}:${NESTJS_PORT}
    # For debugging purposes
    - ${NESTJS_DEBUG_PORT}:${NESTJS_DEBUG_PORT}
    # This runs after development stage is done
    command: npm run start:dev
    env_file:
    - ./server/.docker.env
    networks:
    - postgres
    depends_on:
    - redis
    - postgres

  redis:
    container_name: redis
    image: redis:latest
    env_file:
    - .env
    networks:
    - postgres

  postgres:
    container_name: postgres
    image: postgres:latest
    networks:
    - postgres
    env_file:
    - .env
    ports:
    - ${POSTGRES_PORT}:${POSTGRES_PORT}
    volumes:
    # Host path /data/pgdata is mounted on PGDATA dir in the container.
    - /data/pgadmin:${PGDATA}
    restart: always

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    links:
    - postgres:postgres
    ports:
    - ${PGADMIN_PORT}:80
    volumes:
    # Host path /data/pgadmin is mounted on PGADMIN_DATA dir in the container.
    - /data/postgres:${PGADMIN_DATA}
    env_file:
    - .env
    networks:
    - postgres

networks:
  postgres:
    driver: bridge